# Generated by Django 3.1 on 2020-11-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190930_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='url',
        ),
        migrations.AddField(
            model_name='story',
            name='original_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='product_url',
            field=models.URLField(blank=True),
        ),
    ]
