# Generated by Django 3.1 on 2020-11-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20201105_1227'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='story',
            name='news_story_domain_07db78_idx',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='domain',
            new_name='original_url_domain',
        ),
        migrations.AddField(
            model_name='story',
            name='product_url_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['original_url_domain', 'duplicate_of'], name='news_story_origina_95e3bb_idx'),
        ),
    ]
