# Generated by Django 3.1 on 2020-11-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20201105_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='product_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
