# Generated by Django 3.1 on 2020-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20201107_1143'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='story',
            name='news_story_origina_95e3bb_idx',
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['original_url_domain', 'product_url_domain', 'duplicate_of'], name='news_story_origina_d9ddc2_idx'),
        ),
    ]
