# Generated by Django 3.1 on 2020-11-09 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201105_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='used_invitation',
            field=models.ForeignKey(blank='True', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.invitation'),
        ),
    ]
